sudo: required
services:
  - docker

before_install:
  - docker build -t vijaybh-devops/multi-docker  -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vijaybh-devops/mulit-docker npm test 

after_sucess:
  - docker build -t vijaybh-devops/multi-client  ./client
  - docker build -t vijaybh-devops/multi-nginx  ./nginx
  - docker build -t vijaybh-devops/multi-server  ./server
  - docker build -t vijaybh-devops/multi-worker  ./worker


