sudo: required
services:
  - docker

before_install:
  - docker build -t vijaybh/multi-docker  -f ./client/Dockerfile.dev ./client

script:
        # - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  - docker run -it -e CI=true vijaybh/multi-docker npm run test 

after_sucess:
  - docker build -t vijaybh-devops/multi-client  ./client
  - docker build -t vijaybh-devops/multi-nginx  ./nginx
  - docker build -t vijaybh-devops/multi-server  ./server
  - docker build -t vijaybh-devops/multi-worker  ./worker

# Pushing the file into Docker hub
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  - docker push vijaybh-devops/multi-client
  - docker push vijaybh-devops/multi-nginx
  - docker push vijaybh-devops/multi-server
  - docker push vijaybh-devops/multi-worker
    
