sudo: required
services:
  - docker

before_install:
  - docker build -t vijaybhdevops/multi-docker  -f ./client/Dockerfile.dev ./client

script:
  - docker run -it -e CI=true vijaybhdevops/multi-docker npm run test 

after_sucess:
  - docker build -t vijaybhdevops/multi-client  ./client
  - docker build -t vijaybhdevops/multi-nginx  ./nginx
  - docker build -t vijaybhdevops/multi-server  ./server
  - docker build -t vijaybhdevops/multi-worker  ./worker

# Pushing the file into Docker hub
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  - docker push vijaybhdevops/multi-client
  - docker push vijaybhdevops/multi-nginx
  - docker push vijaybhdevops/multi-server
  - docker push vijaybhdevops/multi-worker
    
